-- 1. Reimicializar tabla de mensajes (Borrar si existe)
DROP TABLE IF EXISTS public.mensajes_resena CASCADE;

-- 2. Crear la tabla
CREATE TABLE public.mensajes_resena (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resena_id bigint NOT NULL REFERENCES public.resenas(id) ON DELETE CASCADE,
    usuario_id bigint NOT NULL,
    usuario_nombre text,
    mensaje text NOT NULL,
    fecha timestamp with time zone DEFAULT now()
);

-- 3. Seguridad y Permisos
ALTER TABLE public.mensajes_resena ENABLE ROW LEVEL SECURITY;

-- Permitir que todos lean los mensajes (Arrendador e Inquilino)
CREATE POLICY "Permitir lectura publica de mensajes" 
ON public.mensajes_resena FOR SELECT 
USING (true);

-- Permitir escribir mensajes (Autenticados o Publico para evitar bloqueo)
CREATE POLICY "Permitir insertar mensajes" 
ON public.mensajes_resena FOR INSERT 
WITH CHECK (true);
